language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 98e1867d86bb07f2afdd3b7b819bf4166089124e0cd71b768927ce57fd332da2
script: yarn run build:ci
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
